/**
 * Ported from rs-map-viewer (BSD-2-Clause, Copyright (c) 2022-2023 dennisdev), see NOTICE.md.
 *
 * OSRS collision-map bit flags and the composite "block" masks the pathfinder
 * tests when stepping in each direction.
 */
const WALL_NORTH_WEST = 0x1
const WALL_NORTH = 0x2
const WALL_NORTH_EAST = 0x4
const WALL_EAST = 0x8
const WALL_SOUTH_EAST = 0x10
const WALL_SOUTH = 0x20
const WALL_SOUTH_WEST = 0x40
const WALL_WEST = 0x80
const OBJECT = 0x100
const WALL_NORTH_WEST_PROJECTILE_BLOCKER = 0x200
const WALL_NORTH_PROJECTILE_BLOCKER = 0x400
const WALL_NORTH_EAST_PROJECTILE_BLOCKER = 0x800
const WALL_EAST_PROJECTILE_BLOCKER = 0x1000
const WALL_SOUTH_EAST_PROJECTILE_BLOCKER = 0x2000
const WALL_SOUTH_PROJECTILE_BLOCKER = 0x4000
const WALL_SOUTH_WEST_PROJECTILE_BLOCKER = 0x8000
const WALL_WEST_PROJECTILE_BLOCKER = 0x10000
const OBJECT_PROJECTILE_BLOCKER = 0x20000
const FLOOR_DECORATION = 0x40000
/** Custom flag: blocks NPCs only (not part of the client's flags). */
const BLOCK_NPCS = 0x80000
/** Custom flag: blocks players (not part of the client's flags). */
const BLOCK_PLAYERS = 0x100000
const FLOOR = 0x200000
const WALL_NORTH_WEST_ROUTE_BLOCKER = 0x400000
const WALL_NORTH_ROUTE_BLOCKER = 0x800000
const WALL_NORTH_EAST_ROUTE_BLOCKER = 0x1000000
const WALL_EAST_ROUTE_BLOCKER = 0x2000000
const WALL_SOUTH_EAST_ROUTE_BLOCKER = 0x4000000
const WALL_SOUTH_ROUTE_BLOCKER = 0x8000000
const WALL_SOUTH_WEST_ROUTE_BLOCKER = 0x10000000
const WALL_WEST_ROUTE_BLOCKER = 0x20000000
const OBJECT_ROUTE_BLOCKER = 0x40000000

const FLOOR_BLOCKED = FLOOR | FLOOR_DECORATION

export const CollisionFlag = {
  WALL_NORTH_WEST,
  WALL_NORTH,
  WALL_NORTH_EAST,
  WALL_EAST,
  WALL_SOUTH_EAST,
  WALL_SOUTH,
  WALL_SOUTH_WEST,
  WALL_WEST,
  OBJECT,
  WALL_NORTH_WEST_PROJECTILE_BLOCKER,
  WALL_NORTH_PROJECTILE_BLOCKER,
  WALL_NORTH_EAST_PROJECTILE_BLOCKER,
  WALL_EAST_PROJECTILE_BLOCKER,
  WALL_SOUTH_EAST_PROJECTILE_BLOCKER,
  WALL_SOUTH_PROJECTILE_BLOCKER,
  WALL_SOUTH_WEST_PROJECTILE_BLOCKER,
  WALL_WEST_PROJECTILE_BLOCKER,
  OBJECT_PROJECTILE_BLOCKER,
  FLOOR_DECORATION,
  BLOCK_NPCS,
  BLOCK_PLAYERS,
  FLOOR,
  WALL_NORTH_WEST_ROUTE_BLOCKER,
  WALL_NORTH_ROUTE_BLOCKER,
  WALL_NORTH_EAST_ROUTE_BLOCKER,
  WALL_EAST_ROUTE_BLOCKER,
  WALL_SOUTH_EAST_ROUTE_BLOCKER,
  WALL_SOUTH_ROUTE_BLOCKER,
  WALL_SOUTH_WEST_ROUTE_BLOCKER,
  WALL_WEST_ROUTE_BLOCKER,
  OBJECT_ROUTE_BLOCKER,

  FLOOR_BLOCKED,

  /* Mixed masks: flags on the *destination* tile that forbid stepping onto it from the given direction. */
  BLOCK_WEST: WALL_EAST | OBJECT | FLOOR_BLOCKED,
  BLOCK_EAST: WALL_WEST | OBJECT | FLOOR_BLOCKED,
  BLOCK_SOUTH: WALL_NORTH | OBJECT | FLOOR_BLOCKED,
  BLOCK_NORTH: WALL_SOUTH | OBJECT | FLOOR_BLOCKED,
  BLOCK_SOUTH_WEST: WALL_NORTH | WALL_NORTH_EAST | WALL_EAST | OBJECT | FLOOR_BLOCKED,
  BLOCK_SOUTH_EAST: WALL_NORTH_WEST | WALL_NORTH | WALL_WEST | OBJECT | FLOOR_BLOCKED,
  BLOCK_NORTH_WEST: WALL_EAST | WALL_SOUTH_EAST | WALL_SOUTH | OBJECT | FLOOR_BLOCKED,
  BLOCK_NORTH_EAST: WALL_SOUTH | WALL_SOUTH_WEST | WALL_WEST | OBJECT | FLOOR_BLOCKED,
  BLOCK_NORTH_AND_SOUTH_EAST:
    WALL_NORTH | WALL_NORTH_EAST | WALL_EAST | WALL_SOUTH_EAST | WALL_SOUTH | OBJECT | FLOOR_BLOCKED,
  BLOCK_NORTH_AND_SOUTH_WEST:
    WALL_NORTH_WEST | WALL_NORTH | WALL_SOUTH | WALL_SOUTH_WEST | WALL_WEST | OBJECT | FLOOR_BLOCKED,
  BLOCK_NORTH_EAST_AND_WEST:
    WALL_NORTH_WEST | WALL_NORTH | WALL_NORTH_EAST | WALL_EAST | WALL_WEST | OBJECT | FLOOR_BLOCKED,
  BLOCK_SOUTH_EAST_AND_WEST:
    WALL_EAST | WALL_SOUTH_EAST | WALL_SOUTH | WALL_SOUTH_WEST | WALL_WEST | OBJECT | FLOOR_BLOCKED,

  /* Route-blocker variants (used for paths that may pass through NPC-blocking-only locs). */
  BLOCK_WEST_ROUTE_BLOCKER: WALL_EAST_ROUTE_BLOCKER | OBJECT_ROUTE_BLOCKER | FLOOR_BLOCKED,
  BLOCK_EAST_ROUTE_BLOCKER: WALL_WEST_ROUTE_BLOCKER | OBJECT_ROUTE_BLOCKER | FLOOR_BLOCKED,
  BLOCK_SOUTH_ROUTE_BLOCKER: WALL_NORTH_ROUTE_BLOCKER | OBJECT_ROUTE_BLOCKER | FLOOR_BLOCKED,
  BLOCK_NORTH_ROUTE_BLOCKER: WALL_SOUTH_ROUTE_BLOCKER | OBJECT_ROUTE_BLOCKER | FLOOR_BLOCKED,
  BLOCK_SOUTH_WEST_ROUTE_BLOCKER:
    WALL_NORTH_ROUTE_BLOCKER |
    WALL_NORTH_EAST_ROUTE_BLOCKER |
    WALL_EAST_ROUTE_BLOCKER |
    OBJECT_ROUTE_BLOCKER |
    FLOOR_BLOCKED,
  BLOCK_SOUTH_EAST_ROUTE_BLOCKER:
    WALL_NORTH_WEST_ROUTE_BLOCKER |
    WALL_NORTH_ROUTE_BLOCKER |
    WALL_WEST_ROUTE_BLOCKER |
    OBJECT_ROUTE_BLOCKER |
    FLOOR_BLOCKED,
  BLOCK_NORTH_WEST_ROUTE_BLOCKER:
    WALL_EAST_ROUTE_BLOCKER |
    WALL_SOUTH_EAST_ROUTE_BLOCKER |
    WALL_SOUTH_ROUTE_BLOCKER |
    OBJECT_ROUTE_BLOCKER |
    FLOOR_BLOCKED,
  BLOCK_NORTH_EAST_ROUTE_BLOCKER:
    WALL_SOUTH_ROUTE_BLOCKER |
    WALL_SOUTH_WEST_ROUTE_BLOCKER |
    WALL_WEST_ROUTE_BLOCKER |
    OBJECT_ROUTE_BLOCKER |
    FLOOR_BLOCKED,
  BLOCK_NORTH_AND_SOUTH_EAST_ROUTE_BLOCKER:
    WALL_NORTH_ROUTE_BLOCKER |
    WALL_NORTH_EAST_ROUTE_BLOCKER |
    WALL_EAST_ROUTE_BLOCKER |
    WALL_SOUTH_EAST_ROUTE_BLOCKER |
    WALL_SOUTH_ROUTE_BLOCKER |
    OBJECT_ROUTE_BLOCKER |
    FLOOR_BLOCKED,
  BLOCK_NORTH_AND_SOUTH_WEST_ROUTE_BLOCKER:
    WALL_NORTH_WEST_ROUTE_BLOCKER |
    WALL_NORTH_ROUTE_BLOCKER |
    WALL_SOUTH_ROUTE_BLOCKER |
    WALL_SOUTH_WEST_ROUTE_BLOCKER |
    WALL_WEST_ROUTE_BLOCKER |
    OBJECT_ROUTE_BLOCKER |
    FLOOR_BLOCKED,
  BLOCK_NORTH_EAST_AND_WEST_ROUTE_BLOCKER:
    WALL_NORTH_WEST_ROUTE_BLOCKER |
    WALL_NORTH_ROUTE_BLOCKER |
    WALL_NORTH_EAST_ROUTE_BLOCKER |
    WALL_EAST_ROUTE_BLOCKER |
    WALL_WEST_ROUTE_BLOCKER |
    OBJECT_ROUTE_BLOCKER |
    FLOOR_BLOCKED,
  BLOCK_SOUTH_EAST_AND_WEST_ROUTE_BLOCKER:
    WALL_EAST_ROUTE_BLOCKER |
    WALL_SOUTH_EAST_ROUTE_BLOCKER |
    WALL_SOUTH_ROUTE_BLOCKER |
    WALL_SOUTH_WEST_ROUTE_BLOCKER |
    WALL_WEST_ROUTE_BLOCKER |
    OBJECT_ROUTE_BLOCKER |
    FLOOR_BLOCKED,
} as const
export type CollisionFlag = (typeof CollisionFlag)[keyof typeof CollisionFlag]
